# Generated by Django 2.2.3 on 2022-12-10 09:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 9, 28, 5, 761054, tzinfo=utc), verbose_name='创建时间'),
        ),
    ]
